### PR TITLE
Add max-respawns parameter to dmon

### PR DESCRIPTION
**Pull request by schultetwin1**
Add a parameter to set a max number of respawns before dmon gives up

### CODE REVIEW

**Review by aperezdc — APPROVED** [review]
@schultetwin1 This is a neat little feature, thanks a lot for the patch :smile:

**Comment by aperezdc** [comment]
Also, I have noticed that it would be handy to propagate the last exit status of the monitored process when using the new `-m`/`--max-respawns` option, so I have added that in commit 85236e660d589be662ba3062a55a21d4cc731868 :hammer_and_wrench:

**Comment by aperezdc** [comment]
@schultetwin1 Also, congratulations on being the first contributor to the project! :tada:

**Comment by schultetwin1** [comment]
> @schultetwin1 Also, congratulations on being the first contributor to the project!

My pleasure! Its a great project!

**Pull request merged**
