### PR TITLE
let drlog create log directory if it doesn't exist

### PR DESCRIPTION
**Pull request by schultetwin1**
drlog currently fails if the log directory does not exist. However, dlog
will create the text log file if it exists. This adds logic to drlog to
create the directory if it does not exist

### CODE REVIEW

**Review by aperezdc — CHANGES_REQUESTED** [review]
Thanks @schultetwin1 for the patch! I think this needs a few changes before merging it, though—please check the comments.

On a more general note, I am not completely sure about merging this functionality, for a number of reasons:

- I think it's perfectly acceptable to have execute `mkdir` by hand before using `drlog`. If you have an use case in which this is impossible (or complicated) and having `drlog` create the directory is better, I would like to hear about it.
- If `drlog` is the one creating the directory, when running under `dmon` the process may be running under the user specified with `-U`/`--log-user`, so at that point it may not have anymore permissions to create the log directory. Example: using `dmon -U loguser servicecmd -- drlog /var/log/service`, when `/var/log` is owned by `root` (which is typical), then `drlog` will never be able to create the directory.
- I prefer to keep the tools included with DMon as minimal as possible.

On the other hand, I would love to hear about your needs, and understand how are you planning to use this feature—knowing more would make me more confident into adding this feature.

At any rate, thanks a lot for your interest in contributing :smiley:

**Comment by aperezdc** [comment]
A couple of doubts more:

- What happens if the directory one level above does not exist? Would we need to implement something like `mkdir -p` inside `drlog`?
- The permissions of the created directories depend on the umask. Would we need to also add some way of specifying their mode?

**Comment by schultetwin1** [comment]
> I think it's perfectly acceptable to have execute mkdir by hand before using drlog. If you have an use case in which this is impossible (or complicated) and having drlog create the directory is better, I would like to hear about it.

I agree, its definitely acceptable to have the user create the directory first. I was just adding this for convenience sake and do not have a use case which is impossible or even complicated. I'll close this PR and just call `mkdir` before using `dmon`.

I also did not think about the permissions bit, that a good point!

Thanks for all the feedback!

**Comment by aperezdc** [comment]
@schultetwin1 You're welcome! And of we can revisit this any time in the future when we stumble upon some case in which it's really needed.

**Pull request closed without merging**
